# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-08 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('processing_started', models.DateTimeField(null=True)),
                ('processing_completed', models.DateTimeField(null=True)),
                ('preprocess', models.BooleanField(default=False)),
                ('preprocess_flags', models.CharField(default=b'{}', max_length=400)),
                ('folder_name', models.CharField(max_length=12)),
                ('input_file_name', models.CharField(max_length=150)),
                ('output_file_name', models.CharField(max_length=160)),
            ],
        ),
    ]
