# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-08 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='preprocess_flags',
            new_name='preprocess_options',
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(default='queued', max_length=20),
        ),
    ]
